name: lpg_distribution_app
description: A digital platform for domestic LPG distribution business.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.0.5

  # Network
  dio: ^5.3.2
  internet_connection_checker: ^1.0.0+1
  http: ^1.2.2

  # Storage
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path_provider: ^2.1.0

  # Utilities
  intl: ^0.18.1
  get_it: ^7.6.0
  rxdart: ^0.27.7
  collection: ^1.17.1
  logger: ^1.4.0
  uuid: ^3.0.7

  # Images
  image_picker: ^1.0.4
  file_picker: ^6.1.1   # For document selection
  photo_view: ^0.14.0
  path: ^1.8.3

  # Bluetooth Printing
  flutter_blue_plus: ^1.14.7

  # Analytics and Monitoring
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4

  # Notifications
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  flutter_secure_storage: ^8.0.0

  #permissions:
  permission_handler: ^10.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  bloc_test: ^9.1.3
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700